import {
  ERROR_CODES,
  type CommentList,
  type CommentNode,
  type CreateCommentInput,
} from 'shared'
import { ApiError } from '../../errors.js'
import type { ArticleService } from '../articles/service.js'
import type { CommentRepository } from './repository.js'

/**
 * Reads whether an account is an administrator.
 *
 * Shaped as a function, not as `AuthRepository`, for one reason: the delete rule
 * below needs exactly one fact about the requester, and naming the dependency by
 * what it answers keeps the comment module from holding a handle on
 * `setAdmin`/`findAllByLogin` — the methods that *grant* the role. The real binding
 * is `AuthRepository.isAdmin` (wired in `routes.ts`), so the answer comes from
 * `users.is_admin` in the database per request, never from a JWT claim, which is
 * defect D1's lesson; and because the seam is one function of one argument, a
 * stand-in for it is one closure.
 *
 * `null` means the account behind the id no longer exists.
 */
export type AdminLookup = (userId: string) => Promise<boolean | null>

export class CommentService {
  constructor(
    private readonly comments: CommentRepository,
    private readonly articles: ArticleService,
    private readonly isAdmin: AdminLookup,
  ) {}

  async listForSlug(slug: string): Promise<CommentList> {
    /**
     * Resolved through the article service rather than re-checking status here.
     *
     * This is why `findPublished` exists as a separate method: the visibility rule
     * has one home, so this endpoint cannot drift out of agreement with the
     * article endpoint about what counts as public. A copied condition would have
     * been one edit away from leaking comments on unpublished articles.
     */
    const article = await this.articles.findPublished(slug)

    return { data: await this.comments.listForArticle(article.id) }
  }

  /**
   * Post a comment, or a reply, on a *published* article.
   *
   * Visibility comes from `findPublished` for the same reason the read path uses
   * it: the rule has one home. A draft — or an article with no publish timestamp —
   * answers 404 ARTICLE_NOT_FOUND here exactly as it does on the detail endpoint,
   * so the comment surface cannot be used to probe for unannounced posts, and
   * cannot be used to graft a comment tree onto content its author never released.
   *
   * `userId` is the verified requester from the token, never a body field: the
   * schema strips unknown keys, so a client that sends `user_id` gets a comment
   * authored by itself instead of the impersonation it asked for.
   *
   * The parent rule (S3-R4: same article, or nothing) is settled by the
   * repository's insert statement rather than by a lookup here, because it is a
   * question about stored rows; see `CommentRepository.insert` for the
   * read-after-write reasoning that decision follows.
   */
  async create(slug: string, input: CreateCommentInput, userId: string): Promise<CommentNode> {
    const article = await this.articles.findPublished(slug)

    const result = await this.comments.insert({
      articleId: article.id,
      userId,
      content: input.content,
      parentId: input.parentId ?? null,
    })

    if (result.kind === 'invalid_parent') {
      throw new ApiError(
        ERROR_CODES.invalidCommentParent,
        'parentId must name a comment on the same article',
        400,
      )
    }

    // Both are "the row we resolved a moment ago is gone": the article deleted
    // between `findPublished` and the insert, or the account deleted while its
    // access token was still valid. They answer the same codes the non-racing
    // requests get — 404 for the article, 401 for an identity that no longer
    // exists, which is the reading `requireAdmin` applies to a null `isAdmin` —
    // instead of becoming a 500 over a `23503` the repository already understood.
    if (result.kind === 'article_missing') {
      throw new ApiError(ERROR_CODES.articleNotFound, `No published article with slug '${slug}'`, 404)
    }

    if (result.kind === 'author_missing') {
      throw new ApiError(ERROR_CODES.unauthorized, 'Account no longer exists', 401)
    }

    // The full node, author included, straight from the statement that wrote it —
    // the client does not reassemble it from its own JWT, so what the list returns
    // and what the create returns cannot disagree about the same comment.
    return result.comment
  }

  /**
   * Delete a comment: author or administrator, nobody else (S3-R5, which closes
   * the permission half of defect D8 — under RLS only `auth.uid() = user_id` could
   * ever delete, so an admin simply could not).
   *
   * ── Why 403 here when a draft *article* is 404 ──────────────────────────────
   * The two answers look inconsistent and are not. They trade different secrets:
   * - A comment id is a uuid generated by the database and never listed anywhere
   *   it shouldn't be, so it is not enumerable. Telling an authenticated caller
   *   "this exists, but it is yours not to delete" leaks a fact nobody could have
   *   obtained except by already holding the id, and that feedback is *useful* —
   *   a client can show "not your comment" instead of a misleading "already gone".
   * - An article slug is guessable text, and whether an unpublished draft exists
   *   under a given slug is precisely the information the write path protects.
   *   A 403 there would be an oracle for unannounced content.
   * So existence-probing is what decides the code, not the verb: the same question
   * gets a different answer because the two resources leak differently. Do not
   * "unify" these — design §2 records the same reasoning for the same reason.
   * ───────────────────────────────────────────────────────────────────────────
   *
   * An unknown id is 404 whether it never existed or was deleted a moment ago, and
   * that includes a reply whose parent has gone: `parent_id` cascades, so deleting
   * a root comment removes its whole thread and every later delete on it answers
   * 404. Same for an author who deleted their own account — `user_id` cascades.
   *
   * A vanished account (`isAdmin` resolves to null) counts as *not* an
   * administrator, and the request stays 403 rather than becoming 401. Different
   * from `requireAdmin`, which answers 401 for null: there, being an admin at all
   * is the question, so "the account you claim to be is gone" is the honest
   * answer. Here the caller's identity is already settled by `requireAuth` — the
   * admin read only feeds the *or*-branch of an authorisation rule, and the
   * authorship branch cannot have matched anyway, because deleting a user cascades
   * their comments away. Downgrading an authorisation miss to an authentication
   * failure would make the code mean something it does not.
   */
  async remove(id: string, requesterId: string): Promise<void> {
    const existing = await this.comments.findById(id)

    if (existing === null) {
      throw new ApiError(ERROR_CODES.notFound, `No comment with id '${id}'`, 404)
    }

    const isAuthor = existing.author.id === requesterId

    if (!isAuthor && (await this.isAdmin(requesterId)) !== true) {
      throw new ApiError(ERROR_CODES.forbidden, 'Not your comment to delete', 403)
    }

    const deleted = await this.comments.deleteById(id)

    if (!deleted) {
      // Lost a race with another deleter; the row is gone either way, so this is
      // the same 404 the pre-check gives and never a 500 or a double-free signal.
      throw new ApiError(ERROR_CODES.notFound, `No comment with id '${id}'`, 404)
    }
  }
}
